version: '3'

tasks:
  gen_migration:
    cmds:
      - migrate create -ext sql -dir migrations -seq {{.CLI_ARGS}}

  migrate:
    vars:
      DB_PATH: reminder.db
    cmds:
      - migrate -source file://migrations -database sqlite3://{{.DB_PATH}} up
  
  bot:
    cmds:
      - go build -o bot.exe
      - .\bot.exe